services:
  server:
    build:
      dockerfile: Dockerfile.min # piper for all models, no gpu/nvidia required, ~1GB
    image: ghcr.io/matatonic/openedai-speech-min
    env_file: speech.env
    ports:
      - "8000:8000"
    volumes:
      - ./voices:/app/voices
      - ./config:/app/config
    # To install as a service
    #restart: unless-stopped
    networks: 
      - open-webui_open_webui_net
networks: 
  open-webui_open_webui_net:
      external: true